[package]
name = "silent_server"
version = "0.1.0"
authors = ["Aleksandr \"Flone\" Tretyakov (github.com/Flone-dnb)"]
edition = "2018"
license = "Zlib"

[dependencies]
platform-dirs = "0.3.0"
bytevec = "0.2.0"
tokio = { version = "1.5.0", features = ["full"] }
futures = "0.3.14"
chrono = "0.4.19"